apiVersion: v1
kind: Pod
metadata:
  name: s3-client
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sh", "-c", "sleep 3600"]
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: ceph-s3-secret
            key: accessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: ceph-s3-secret
            key: secretKey
      - name: AWS_DEFAULT_REGION
        value: us-east-1
