apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name for the cluster-wide role
  name: pod-reader-cluster
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
